"""tut_upload.py — YouTube uploader for TurntUpToddler channel.

Usage:
    python tut_upload.py --video song.mp4 --title "..." --genre psytrance
    python tut_upload.py --batch           # upload all generated videos

Auth: Put client_secrets.json in hymn_remaker/tut_client_secrets.json
"""
import os
import sys
import json
import argparse
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

ROOT = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(ROOT)
TOKEN_PATH = os.path.join(BASE, "tut_token.json")
SECRETS_PATH = os.path.join(BASE, "tut_client_secrets.json")
SCOPES = ["https://www.googleapis.com/auth/youtube"]
VIDEO_DIR = os.path.join(BASE, "videos")

from google_auth_oauthlib.flow import InstalledAppFlow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload


def get_authenticated_service():
    creds = None
    if os.path.exists(TOKEN_PATH):
        with open(TOKEN_PATH) as f:
            data = json.load(f)
        creds = Credentials.from_authorized_user_info(data, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(SECRETS_PATH):
                print(f"Missing {SECRETS_PATH}")
                print("Download from Google Cloud Console → YouTube Data API v3 → OAuth 2.0 Client ID")
                return None
            flow = InstalledAppFlow.from_client_secrets_file(SECRETS_PATH, SCOPES)
            creds = flow.run_local_server(port=8080)
            with open(TOKEN_PATH, "w") as f:
                f.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)


def upload_video(video_path, title, description="", tags=None, privacy="public"):
    if not os.path.exists(video_path):
        print(f"  Video not found: {video_path}")
        return None

    youtube = get_authenticated_service()
    if not youtube:
        return None

    size = os.path.getsize(video_path)
    print(f"  Uploading: {os.path.basename(video_path)} ({size // 1024 // 1024}MB)")

    body = {
        "snippet": {
            "title": title[:100],
            "description": description[:5000],
            "tags": (tags or [])[:500],
            "categoryId": "10",  # Music
        },
        "status": {"privacyStatus": privacy},
    }

    media = MediaFileUpload(video_path, chunksize=4 * 1024 * 1024, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    response = None
    last_progress = 0
    while response is None:
        status, response = request.next_chunk()
        if status:
            progress = int(status.progress() * 100)
            if progress >= last_progress + 10:
                print(f"     {progress}%")
                last_progress = progress

    video_id = response.get("id", "?")
    print(f"  Uploaded: https://youtu.be/{video_id}")
    return video_id


def build_metadata(song, genre_slug, speed, vocal_mode, genre_desc):
    """Build title, description, tags from song metadata."""
    song_title = song.replace("_", " ").title()
    genre_name = genre_slug.replace("_", " ")
    speed_str = f"{speed}x"
    vocal_str = "with lyrics" if vocal_mode == "lyrics" else "instrumental"

    title = f"{song_title} | {genre_name} {speed_str} {vocal_str} | TurntUpToddler"
    description = (
        f"{song_title} — remixed as {genre_desc}\n"
        f"Speed: {speed_str} | Vocal: {vocal_str}\n\n"
        "Generated by TurntUpToddler — AI-powered children's music remixer.\n"
        "Audio: Suno AI | Video: Kling AI\n"
        f"Genre: {genre_name}\n"
    )
    tags = [
        "childrens music", "nursery rhyme", genre_slug, song,
        "ai music", "turntuptoddler", "edm", "remix",
    ]
    return title, description, tags


def main():
    parser = argparse.ArgumentParser(description="TUT YouTube Uploader")
    parser.add_argument("--video", help="Video file to upload")
    parser.add_argument("--title", help="Title")
    parser.add_argument("--genre", default="psytrance")
    parser.add_argument("--batch", action="store_true", help="Upload all videos in videos/")
    parser.add_argument("--privacy", default="public", choices=["public", "unlisted", "private"])
    args = parser.parse_args()

    if args.batch:
        if not os.path.isdir(VIDEO_DIR):
            print(f"No videos directory: {VIDEO_DIR}")
            return
        videos = sorted([f for f in os.listdir(VIDEO_DIR) if f.endswith(".mp4")])
        print(f"Found {len(videos)} videos")
        for vf in videos:
            vp = os.path.join(VIDEO_DIR, vf)
            # Parse song_genre_speed_vocal from filename
            base = vf.replace(".mp4", "")
            parts = base.split("_")
            # Format: {song}_{genre}_speed_{speed}_{vocal}
            if "speed" in base:
                sp_idx = [i for i, p in enumerate(parts) if p == "speed"]
                if sp_idx:
                    song = "_".join(parts[: sp_idx[0] - 1])
                    genre = parts[sp_idx[0] - 1]
                    speed_str = parts[sp_idx[0] + 1]
                    speed = float(speed_str)
                    vocal = parts[-1] if len(parts) > sp_idx[0] + 1 else "instrumental"
                    genre_desc = genre.replace("_", " ")
                    title, desc, tags = build_metadata(song, genre, speed, vocal, genre_desc)
                    print(f"\n{vf}")
                    upload_video(vp, title, desc, tags)
    else:
        if not args.video or not args.title:
            print("Usage: python tut_upload.py --video <file> --title <title>")
            return
        description = f"Generated by TurntUpToddler — {args.genre} remix."
        tags = ["childrens music", "nursery rhyme", args.genre, "ai music", "turntuptoddler"]
        upload_video(args.video, args.title, description, tags)


if __name__ == "__main__":
    main()
